stages:
  - build

build:
  stage: build
  tags: [docker]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    - |
      if [ "$CI_BUILD_REF_NAME" == "master" ]
      then
        export ENV_VERSION=latest
      else
        export ENV_VERSION=$CI_BUILD_REF_NAME
      fi
  script:
    - docker build -f docker/Dockerfile -t ansible .
    - docker tag ansible $CI_REGISTRY_IMAGE:$ENV_VERSION
    - docker push $CI_REGISTRY_IMAGE:$ENV_VERSION
  only:
    - master
